import { Store } from "pullstate";

const DrinkQueryStore = new Store({
  categories: [
    "Ordinary Drink",
    "Cocktail",
    "Shot",
    "Punch / Party Drink",
    "Beer",
    "Homemade",
    "Soft Drink",
    "Shake",
    "Other / Unknown",
    "Cocoa",
    "Coffee / Tea",
  ],
  ingredients: [
    "Absolut Citron",
    "Ale",
    "Amaretto",
    "Angelica root",
    "Apple brandy",
    "Apple cider",
    "Apple juice",
    "Applejack",
    "Apricot brandy",
    "Añejo rum",
    "Bitters",
    "Blackberry brandy",
    "Blended whiskey",
    "Bourbon",
    "Brandy",
    "Carbonated water",
    "Cantaloupe",
    "Coffee",
    "Coffee brandy",
    "Coffee liqueur",
    "Cognac",
    "Cocoa powder",
    "Chocolate",
    "Chocolate liqueur",
    "Chocolate syrup",
    "Cider",
    "Coffee liqueur",
    "Cranberries",
    "Cranberry juice",
    "Creme de Cacao",
    "Creme de Cassis",
    "Dark rum",
    "Demerara Sugar",
    "Dry Vermouth",
    "Dubonnet Rouge",
    "Egg",
    "Egg yolk",
    "Espresso",
    "Everclear",
    "Firewater",
    "Galliano",
    "Gin",
    "Ginger",
    "Grape juice",
    "Grapefruit juice",
    "Grapes",
    "Grenadine",
    "Heavy cream",
    "Irish cream",
    "Irish whiskey",
    "Johnnie Walker",
    "Kahlua",
    "Kiwi",
    "Lager",
    "Lemon",
    "Lemon juice",
    "Lemon vodka",
    "Lemonade",
    "Lime",
    "Lime juice",
    "Mango",
    "Midori melon liqueur",
    "Milk",
    "Ouzo",
    "Orange",
    "Orange bitters",
    "Peach nectar",
    "Peach Vodka",
    "Peppermint schnapps",
    "Pineapple juice",
    "Pisco",
    "Port",
    "Red wine",
    "Ricard",
    "Rum",
    "Scotch",
    "Sherry",
    "Sloe gin",
    "Southern Comfort",
    "Sugar",
    "Sugar syrup",
    "Sprite",
    "Sambuca",
    "Strawberries",
    "Strawberry schnapps",
    "Sweet Vermouth",
    "Tea",
    "Tequila",
    "Tomato juice",
    "Triple sec",
    "Vodka",
    "Water",
    "Watermelon",
    "Whiskey",
    "Yoghurt",
  ],
});

export default DrinkQueryStore;
